doctrine:
  dbal:
    charset: utf8
    server_version: '11.5'
    driver: pdo_pgsql
    user: '%env(resolve:POSTGRES_USER)%'
    password: '%env(resolve:POSTGRES_PASSWORD)%'
    dbname: '%env(resolve:POSTGRES_DB)%'
    host: '%env(resolve:PSQL_HOST)%'
    port: '%env(resolve:PSQL_PORT)%'

  orm:
    auto_generate_proxy_classes: false
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Entities:
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'

doctrine_migrations:
  migrations_paths:
    'DoctrineMigrations': '%kernel.project_dir%/migrations'
  enable_profiler: '%kernel.debug%'

framework:
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.system_cache_pool:
        adapter: cache.system