http:
  # middlewares:
  #   www-remover:
  #     redirectregex:
  #       regex: ^https://www\.(.*)
  #       replacement: https://$1

  # routers:
  #   www-router:
  #     rule: HostRegexp(`{host:www\..+}`)
  #     tls: true
  #     service: noop@internal
  #     middlewares: www-remover

tls:
  certificates:
    - certFile: /etc/traefik/certs/jurcorpus.crt
      keyFile: /etc/traefik/certs/jurcorpus.key
  options:
    default:
      sniStrict: true