global:
  sendAnonymousUsage: false

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: traefik-public
  file:
    filename: /etc/traefik/dynamic_conf.yml

entrypoints:
  web:
    address: :80
    forwardedHeaders:
      insecure: true
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    # asDefault: true

### METRICS:
metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true


### LOGS:
# log:
  # filePath: /etc/logs/traefik.log
  # format: json
  # INFO \ DEBUG \
  # level: INFO

accesslog:
  format: common # common, json, logfmt
  filePath: /etc/logs/access.log